name: 3pslcca
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - osdag::osdag_latex_env
  - pip:
    - PySide6
    - psutil
    - Pillow
    - matplotlib
    - git+https://github.com/swas02/3psLCCA-core.git@main
