name: 3pslcca
channels:
  - conda-forge
  - osdag
  - zehen-249
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - openpyxl
  - PyYAML
  - pylatex
  - osdag_latex_env
  - pip:
    - PySide6
    - psutil
    - Pillow
    - matplotlib
    - platformdirs
    - git+https://github.com/swas02/3psLCCA-core.git@main
