name: 3pslcca
channels:
  - conda-forge
  - osdag
  - zehen-249
  - nodefaults
dependencies:
  - python>=3.10,<3.13
  - pyside6<6.10
  - psutil
  - Pillow
  - matplotlib
  - pandas
  - numpy
  - openpyxl
  - PyYAML
  - pylatex
  - three-ps-lcca-core
  - osdag::osdag_latex_env
  - platformdirs
