{% set name = "three-ps-lcca-gui" %}
{% set version = "1.0.0" %}
{% set git_url = "https://github.com/swas02/3psLCCA-gui.git" %}
{% set branch = "main" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: {{ source_url }}
  # git_url: {{ git_url }}
  # git_rev: {{ branch }}

  path: ..

build:
  number: 0
  noarch: python
  script:  "{{ PYTHON }} -m pip install --no-deps --ignore-installed --force-reinstall . -vv"
  entry_points:
    - threePSLCCA = three_ps_lcca_gui.gui.main:main

channel:
  - conda-forge
  - defaults
  - osdag
  - zehen-249

requirements:
  build:
    - python>=3.10,<3.13
    - setuptools
    - pip
  host:
    - setuptools
    - pip
    - python>=3.10,<3.13
  run:
    - python>=3.10,<3.13
    - pyside6<6.10
    - psutil
    - Pillow
    - matplotlib
    - pandas
    - numpy
    - openpyxl
    - PyYAML
    - pylatex
    - three-ps-lcca-core
    - osdag::osdag_latex_env
    - platformdirs

about:
  summary: >-
    A Python package for performing life cycle cost analysis (LCCA) on three
    primary steel design options: hot-rolled, cold-formed, and built-up steel
    sections. This package provides tools and functions to evaluate the economic
    performance of these steel design options over their entire life cycle,
    including initial costs, maintenance costs, and end-of-life costs. It is
    designed to assist engineers and decision-makers in selecting the most
    cost-effective steel design option for their projects.